version: "3.1"

services:
  bot:
    image: gusgus153/rksi_hak_bot
    build: .
    container_name: bot
    depends_on:
      - db
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthcheck"]
      interval: 5s
      timeout: 10s
      retries: 3
    environment:
      - TZ=Europe/Moscow    

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    volumes:
    - db:/db/volumes
    

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    volumes:
    - adminer:/adminer/volumes

volumes:
  db:
  adminer: